name: Theme Quality Assurance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  accessibility-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync
        
    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Validate theme JSON
      run: just validate

    - name: Run accessibility tests
      run: just test

    - name: Quick contrast check
      run: just quick-test
        
    - name: Check for old color values
      run: |
        echo "Checking for outdated color values..."
        if grep -r "#059669\|#d97706\|#7c7c7c" themes/ --exclude="*.md"; then
          echo "⚠️ Found old color values that need updating"
          exit 1
        else
          echo "✅ No outdated color values found"
        fi

  build-test:
    runs-on: ubuntu-latest
    needs: accessibility-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install vsce
      run: npm install -g vsce

    - name: Build VSIX package
      run: just build

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: '*.vsix'
        retention-days: 30

    - name: Validate package contents
      run: |
        echo "Validating package contents..."
        unzip -l *.vsix
        unzip -t *.vsix
        echo "✅ VSIX package is valid"
